invenio_workflows_ui/ext.py, invenio_workflows_ui/search.py, invenio_workflows_ui/utils.py, invenio_workflows_ui/views/rest.py, invenio_workflows_ui/views/ui.py
Signed-off-by: Jan Aage Lavik <jan.age.lavik@cern.ch>
Signed-off-by: Javier Martin Montull <javier.martin.montull@cern.ch>
=> global: move to elasticsearch-dsl

invenio_workflows_ui/mappings/workflows/record.json
Signed-off-by: Guillaume Lastecoueres <guillaume.lastecoueres@techie.com>
=> mappings: enable->enabled typo

invenio_workflows_ui/permissions.py, invenio_workflows_ui/views/rest.py, invenio_workflows_ui/views/ui.py, setup.py
Signed-off-by: Javier Martin Montull <javier.martin.montull@cern.ch>
=> WIP permissions: holdingpen-admin-access action addition

invenio_workflows_ui/permissions.py, invenio_workflows_ui/views/rest.py, invenio_workflows_ui/views/ui.py
* Allows only users with workflows-ui-admin-access action allowed
to perform requests to views. (addresses #920)
Signed-off-by: Javier Martin Montull <javier.martin.montull@cern.ch>
=> permissions: restrict API views

invenio_workflows_ui/api.py
=> api: reset workflow status on resume/restart

invenio_workflows_ui/api.py, invenio_workflows_ui/permissions.py, invenio_workflows_ui/views/rest.py, setup.py
=> Pin to the invenio-workflows major version.

invenio_workflows_ui/cli.py, invenio_workflows_ui/ext.py
* Adds reindex command that allows sending to ElasticSearch all workflows
present in the database (based on the data type).
Signed-off-by: Javier Martin Montull <javier.martin.montull@cern.ch>
=> cli: initial commit

invenio_workflows_ui/api.py
=> workflowuirecord: restart form first task

invenio_workflows_ui/cli.py
* Uses yield in order to reindex a holdingpen index.
(closes #27)
Signed-off-by: Samuele Kaplun <samuele.kaplun@cern.ch>
=> cli: reindex via yield_per

invenio_workflows_ui/cli.py
Signed-off-by: Samuele Kaplun <samuele.kaplun@cern.ch>
=> cli: bulk reindexing

setup.py
Signed-off-by: Zacharias Zacharodimos <zacharias.zacharodimos@cern.ch>
=> bump `invenio_workflows` to version 7

invenio_workflows_ui/api.py, setup.py
This partially addresses
https://github.com/inspirehep/inspire-next/issues/3069
=> WorkflowUIObject: allow cleanup on restart

invenio_workflows_ui/cli.py
=> cli: properly format failures on error

.gitignore, invenio_workflows_ui/permissions.py, invenio_workflows_ui/views/rest.py, setup.py
=> permissions: allow fine-grained read/write actions

invenio_workflows_ui/cli.py, invenio_workflows_ui/tasks.py
- Instead of indexing records in bulk synchronously in the same thread, schedule celery tasks in order to support parallel indexing.
- Adds a new command line argument to `reindex`: `-s` or `--batch-size`, number of records to be reindex in one task.
- The tasks are pushed onto the celery queue named `indexer_tasks`.
=> cli: parallelise HP indexing between workers

invenio_workflows_ui/cli.py
Signed-off-by: Szymon Łopaciuk <szymon@lopaciuk.eu>
=> cli: remap: write errors to a file not stdout

invenio_workflows_ui/serializers/response.py, invenio_workflows_ui/views/rest.py, tests/test_invenio_workflows_serializer_response.py
Signed-off-by: Harris Tzovanakis <me@drjova.com>
=> response: addition of etag header

invenio_workflows_ui/views/rest.py
Signed-off-by: Szymon Łopaciuk <szymon@lopaciuk.eu>
=> views.rest: add restart_step to action segment

setup.py
=> global: remove elasticsearch2 compatibility

invenio_workflows_ui/mappings/v5/workflows/record.json
=> es5: adapt mappings
